# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0005_auto_20180312_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
