# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0008_auto_20180315_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answervotes',
            name='votes',
        ),
        migrations.AddField(
            model_name='answervotes',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
