# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import quora.models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0010_auto_20180319_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=200, validators=[quora.models.validate_text]),
        ),
        migrations.AlterField(
            model_name='answervotes',
            name='value',
            field=models.IntegerField(default=0, validators=[quora.models.validate_vote]),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[quora.models.validate_date], verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=256, validators=[quora.models.validate_text]),
        ),
        migrations.AlterField(
            model_name='questionvotes',
            name='value',
            field=models.IntegerField(default=0, validators=[quora.models.validate_vote]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_text',
            field=models.CharField(max_length=256, validators=[quora.models.validate_text]),
        ),
    ]
